#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#export PATH=$PATH:~/opt/dotfiles/scripts/:~/.cargo/bin/:/usr/local/go/bin:~/opt/goland/current/bin/
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH
export JAVA_HOME=$(/usr/libexec/java_home)
#source ~/.ssh/secrets

export EDITOR=nvim

alias ll="exa -lr"
alias vim=nvim
alias ag=rg
alias loc="git ls-files | xargs wc -l"
alias branchgc="git checkout master;git branch --merged | grep -v master|awk '{print \"git branch -d\" \$0;}'|bash"
#alias vim='nvim'

# Setting ag as the default source for fzf
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
