#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/kiril/.sdkman"
[[ -s "/Users/kiril/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/kiril/.sdkman/bin/sdkman-init.sh"
if [  ]; then source <(kubectl completion zsh); fi

color-ssh() {
    trap "colorterm" EXIT
    if [[ "$*" =~ "prod" ]]; then
        colorterm prod
    elif [[ "$*" =~ "staging" ]]; then
        colorterm staging
    else
        colorterm other
    fi
    ssh $*
  }
compdef _ssh color-ssh=ssh
# alias ssh=color-ssh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/kiril/opt/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/kiril/opt/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/kiril/opt/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/kiril/opt/google-cloud-sdk/completion.zsh.inc'; fi

# added by travis gem
[ -f /Users/kiril/.travis/travis.sh ] && source /Users/kiril/.travis/travis.sh
